#include "priskribo.h"
#include "ui_priskribo.h"

void priskribo::priVakigu()
{ui->teksto->clear();
 if(enigojAktivigita[PRISKRIBO_REFERENCEITA])
  ui->cite->setText("<a>");
 if(enigojAktivigita[PRISKRIBO_CITAJXO])
  ui->cite->setText("<cite>");
 if(enigojAktivigita[PRISKRIBO_TITOLOUNUA])
  ui->h1->setText("<h1>");
 if(enigojAktivigita[PRISKRIBO_TITOLODUA])
  ui->h2->setText("<h2>");
 if(enigojAktivigita[PRISKRIBO_TITOLOTRIA])
  ui->h3->setText("<h3");
 if(enigojAktivigita[PRISKRIBO_TITOLOKVARA])
  ui->h4->setText("<h4>");
 if(enigojAktivigita[PRISKRIBO_TITOLOKVINA])
  ui->h5->setText("<h5>");
 if(enigojAktivigita[PRISKRIBO_TITOLOSESA])
  ui->h6->setText("<h6>");
 if(enigojAktivigita[PRISKRIBO_PARAGRAFO])
  ui->p->setText("<p>");
 if(enigojAktivigita[PRISKRIBO_SEKCIO])
  ui->div->setText("<div>");
 if(enigojAktivigita[PRISKRIBO_BLOKOCITAJXO])
  ui->blockquote->setText("<blockquote>");
 if(enigojAktivigita[PRISKRIBO_FIGURO])
  ui->figure->setText("<figure>");
 if(enigojAktivigita[PRISKRIBO_FIGUROTITOLO])
  ui->figcaption->setText("<figcaption>");
 if(enigojAktivigita[PRISKRIBO_MARGXENO])
  ui->aside->setText("<aside>");
 if(enigojAktivigita[PRISKRIBO_GRASA])
  ui->b->setText("<b>");
 if(enigojAktivigita[PRISKRIBO_FORTA])
  ui->strong->setText("<strong>");
 if(enigojAktivigita[PRISKRIBO_KURSIVA])
  ui->i->setText("<i>");
 if(enigojAktivigita[PRISKRIBO_EMFAZA])
  ui->em->setText("<em>");
 if(enigojAktivigita[PRISKRIBO_DIFINO])
  ui->dfn->setText("<dfn>");
 if(enigojAktivigita[PRISKRIBO_SPECIMENO])
  ui->samp->setText("<samp>");
 if(enigojAktivigita[PRISKRIBO_KODO])
  ui->code->setText("<code>");
 if(enigojAktivigita[PRISKRIBO_APRIORA])
  ui->pre->setText("<pre>");
 if(enigojAktivigita[PRISKRIBO_SUBSTRETIKA])
  ui->u->setText("<u>");
 if(enigojAktivigita[PRISKRIBO_SUPERSKRIBITA])
  ui->sup->setText("<sup>");
 if(enigojAktivigita[PRISKRIBO_SUBA])
  ui->sub->setText("<sub>");
 if(enigojAktivigita[PRISKRIBO_MINORA])
  ui->small->setText("<small>");
 if(enigojAktivigita[PRISKRIBO_NEORDIGITALISTO])
  ui->ul->setText("<ul>");
 if(enigojAktivigita[PRISKRIBO_ORDIGITALISTO])
  ui->ol->setText("<ol>");
 if(enigojAktivigita[PRISKRIBO_LISTOERO])
  ui->li->setText("<li>");
 if(enigojAktivigita[PRISKRIBO_DIFINOLISTO])
  ui->dl->setText("<dl>");
 if(enigojAktivigita[PRISKRIBO_DIFINOLISTOERO])
  ui->dt->setText("<dt>");
 if(enigojAktivigita[PRISKRIBO_DIFINOLISTOTEKSTO])
  ui->dd->setText("<dd>");
 if(enigojAktivigita[PRISKRIBO_TABELO])
  ui->table->setText("<table>");
 if(enigojAktivigita[PRISKRIBO_TABELOKAPO])
  ui->thead->setText("<thead>");
 if(enigojAktivigita[PRISKRIBO_TABELOVICO])
  ui->tr->setText("<tr>");
 if(enigojAktivigita[PRISKRIBO_TABELOCXELO])
  ui->td->setText("<td>");
 for(int indekso=0;indekso<36;++indekso)
  enigojAktivigita[indekso]=false;
}
